
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async connectToDb(dbPath: string) : Promise<Result<null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_to_db", { dbPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async queryTags(tagName: string, count: number) : Promise<TagQueryOutput[]> {
    return await TAURI_INVOKE("query_tags", { tagName, count });
},
async queryAll(width: number, imgHeight: number, gaps: number) : Promise<ImageRow[] | null> {
    return await TAURI_INVOKE("query_all", { width, imgHeight, gaps });
},
async getThumbnail(hash: string) : Promise<Result<string | null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_thumbnail", { hash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInfo(hash: string) : Promise<MediaInfo | null> {
    return await TAURI_INVOKE("get_info", { hash });
},
async getLayoutFromCache(width: number, imgHeight: number, gaps: number) : Promise<ImageRow[] | null> {
    return await TAURI_INVOKE("get_layout_from_cache", { width, imgHeight, gaps });
},
async updateTags(rawInput: string, hash: string) : Promise<void> {
    await TAURI_INVOKE("update_tags", { rawInput, hash });
},
async getTags(hash: string) : Promise<MediaTag[] | null> {
    return await TAURI_INVOKE("get_tags", { hash });
},
/**
 * gets the provided env var, returns an empty string if the env var doesn't exist or something goes wrong
 */
async getEnvVar(envvar: string) : Promise<string> {
    return await TAURI_INVOKE("get_env_var", { envvar });
},
async areDbsMounted() : Promise<boolean> {
    return await TAURI_INVOKE("are_dbs_mounted");
},
async getConfig() : Promise<GlobalConfig> {
    return await TAURI_INVOKE("get_config");
},
/**
 * Mounts the dbs into db_store, runs any pending migrations
 */
async connectDbs() : Promise<void> {
    await TAURI_INVOKE("connect_dbs");
},
async getThumbnailFromDb(hash: string) : Promise<string | null> {
    return await TAURI_INVOKE("get_thumbnail_from_db", { hash });
},
async getThumbsDbInfo() : Promise<ThumbsDBInfo | null> {
    return await TAURI_INVOKE("get_thumbs_db_info");
},
async setConfigValue(category: string, key: string, valu: string) : Promise<void> {
    await TAURI_INVOKE("set_config_value", { category, key, valu });
},
async setConfigResolutionValue(height: number, width: number) : Promise<void> {
    await TAURI_INVOKE("set_config_resolution_value", { height, width });
},
/**
 * `input_raw`: user tags
 * `width`: viewport width for layout
 * `gaps`: gaps between images
 */
async search(inputRaw: string, width: number, gaps: number) : Promise<void> {
    await TAURI_INVOKE("search", { inputRaw, width, gaps });
},
/**
 * Returns the pointer to close the server
 */
async serveMedia(hash: string) : Promise<void> {
    await TAURI_INVOKE("serve_media", { hash });
},
/**
 * This should be only called once from js side
 */
async closeServer() : Promise<void> {
    await TAURI_INVOKE("close_server");
},
async getMediaType(hash: string) : Promise<string> {
    return await TAURI_INVOKE("get_media_type", { hash });
},
/**
 * Adds a single index source from the path, does not index that path without calling index_path()
 */
async addIndexSource(path: string) : Promise<void> {
    await TAURI_INVOKE("add_index_source", { path });
},
async removeIndexSource(path: string) : Promise<void> {
    await TAURI_INVOKE("remove_index_source", { path });
},
async getIndexPaths() : Promise<string[]> {
    return await TAURI_INVOKE("get_index_paths");
},
async indexAll() : Promise<Result<null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("index_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadAndIndex(url: string) : Promise<void> {
    await TAURI_INVOKE("download_and_index", { url });
},
async indexPath(path: string) : Promise<void> {
    await TAURI_INVOKE("index_path", { path });
},
async imagePathToRgbaBytes(path: string) : Promise<RawImage> {
    return await TAURI_INVOKE("image_path_to_rgba_bytes", { path });
},
async openWithSystemDefaultApp(path: string) : Promise<void> {
    await TAURI_INVOKE("open_with_system_default_app", { path });
},
async newLinuxFilePickerDialog() : Promise<string[]> {
    return await TAURI_INVOKE("new_linux_file_picker_dialog");
},
async nukeAllIndexes() : Promise<void> {
    await TAURI_INVOKE("nuke_all_indexes");
},
async nukeSelectedIndex(path: string) : Promise<void> {
    await TAURI_INVOKE("nuke_selected_index", { path });
},
async cleanupUnreferencedFiles() : Promise<void> {
    await TAURI_INVOKE("cleanup_unreferenced_files");
},
async getSwfResolution(path: string) : Promise<[number, number]> {
    return await TAURI_INVOKE("get_swf_resolution", { path });
},
async getGroupInfo(groupHash: string) : Promise<MediaInfo[]> {
    return await TAURI_INVOKE("get_group_info", { groupHash });
},
async deleteTags(hash: string, tags: string[]) : Promise<void> {
    await TAURI_INVOKE("delete_tags", { hash, tags });
},
async getTagsAsText(hash: string) : Promise<string | null> {
    return await TAURI_INVOKE("get_tags_as_text", { hash });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Database = { db_path: string }
export type Downloader = { output_path: string; gdl_config_path: string | null }
export type GlobalConfig = { Database: Database; Thumbnails: Thumbs; Downloader: Downloader }
export type ImagePlacement = { x_relative: number; y_relative: number; width: number; height: number; hash: string }
export type ImageRow = { index: number; height: number; images: ImagePlacement[] }
export type ImportInfo = { importSource: string; importLink: string | null }
export type MediaInfo = { meta: MetaEntry[]; import: ImportInfo; paths: string[]; tags: MediaTag[]; tagsWithSourceTypes: SourceGroupedTags; rawTagsField: string; hash: string; mediaType: string; mime: string | null; aspectRatio: number; fileName: string }
export type MediaTag = { name: string; sourceCategory: string | null }
export type MetaEntry = { name: string; value: string; isValueMonospaced: boolean; isOneLine: boolean }
export type RawImage = { width: number; height: number; bytes: number[] }
export type SourceGroupedTags = { source_categories: { [key in string]: MediaTag[] }; uncategorized: MediaTag[] }
/**
 * Additional Tag details, all info about tags is here instead of `Tag` table, so we don't deal with limitations
 * of virtual tables
 */
export type TagDetail = { name: string; 
/**
 * Should the tag be deleted when there is no `HashTagPair`s containing this tag left
 */
delete_on_no_references_left: boolean; color: string | null; group: string | null; 
/**
 * Should this tag use its own color instead of the group one
 */
override_group_color: boolean }
export type TagQueryOutput = { name: string; count: number; tag_details: TagDetail }
export type ThumbnailFormat = "png" | "jpeg" | "avif"
export type Thumbs = { resolution: [number, number]; thumbnail_format: ThumbnailFormat; thumbs_db_path: string }
export type ThumbsDBInfo = { path: string; size: string; image_count: number; height: number; width: number; format: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
