CREATE TABLE IF NOT EXISTS MediaEmbeddingMeta (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hash TEXT NOT NULL UNIQUE
);

CREATE VIRTUAL TABLE IF NOT EXISTS MediaEmbedding USING vec0 (
    id INTEGER PRIMARY KEY,
    embedding FLOAT[768]
);