[package]
name = "kasa_ai"
version = "0.1.0"
edition = "2024"

[dependencies]
ort = { version = "2.0.0-rc.11", features = [
    "cuda",
    "rocm",
    "load-dynamic",
] } # should we build it from source?
ndarray = "0.17.2"
csv = { version = "1.3.1" }
image = { workspace = true }
serde = { workspace = true, features = ["derive"] }
anyhow.workspace = true
fastembed = "5.13.0"
